# Generated by Django 5.2.5 on 2025-08-31 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('expense', 'expense'), ('income', 'income')], default='expense', max_length=20),
        ),
    ]
