# Generated by Django 5.2.5 on 2025-08-31 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_delete_category_alter_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], default='Expense', max_length=20),
        ),
    ]
