# Generated by Django 5.2.5 on 2025-08-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('expense', 'expense'), ('income', 'income')], default='Expense', max_length=20),
        ),
    ]
