# Generated by Django 5.1.13 on 2025-11-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_expense_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="type",
            field=models.CharField(
                choices=[("Expense", "Expense"), ("Income", "Income")],
                default="Expense",
                max_length=20,
            ),
        ),
    ]
