# Generated by Django 5.1.13 on 2025-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_lendborrow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lendborrow",
            old_name="type",
            new_name="transaction_type",
        ),
        migrations.RemoveField(
            model_name="lendborrow",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="lendborrow",
            name="note",
        ),
        migrations.AddField(
            model_name="lendborrow",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Settled", "Settled")],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
