# Generated by Django 5.1.13 on 2025-11-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_rename_type_lendborrow_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lendborrow",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="transaction_type",
            field=models.CharField(
                choices=[("borrowed", "Borrowed"), ("lent", "Lent")], max_length=10
            ),
        ),
    ]
