# Generated by Django 5.2.5 on 2025-11-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_lendborrow_due_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lendborrow",
            name="person_name",
        ),
        migrations.RemoveField(
            model_name="lendborrow",
            name="transaction_type",
        ),
        migrations.AddField(
            model_name="lendborrow",
            name="person",
            field=models.CharField(default="Unknown Person", max_length=100),
        ),
        migrations.AddField(
            model_name="lendborrow",
            name="type",
            field=models.CharField(
                choices=[("borrowed", "Borrowed"), ("lent", "Lent")],
                default="borrowed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("settled", "Settled")],
                default="pending",
                max_length=20,
            ),
        ),
    ]
