# Generated by Django 5.2.5 on 2025-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_remove_lendborrow_person_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lendborrow",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="person",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="type",
            field=models.CharField(
                choices=[("lent", "Lent"), ("borrowed", "Borrowed")],
                default="borrowed",
                max_length=10,
            ),
        ),
    ]
