# Generated by Django 5.2.5 on 2025-11-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_alter_expense_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=100),
        ),
    ]
