# Generated by Django 5.2.5 on 2025-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_alter_expense_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=50),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
