# Generated by Django 5.2.5 on 2025-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_alter_expense_item_name_alter_lendborrow_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="item_name",
            field=models.CharField(default="Unknown Item", max_length=100),
        ),
        migrations.AlterField(
            model_name="lendborrow",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
